- name: Install Android SDK (FIX LICENSE + AIDL)
  run: |
    export ANDROID_HOME=$HOME/android-sdk
    mkdir -p $ANDROID_HOME/cmdline-tools

    cd $HOME
    wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
    unzip commandlinetools-linux-*.zip -d $ANDROID_HOME/cmdline-tools

    mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

    export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH

    yes | sdkmanager --licenses || true
    yes | sdkmanager --licenses || true
    yes | sdkmanager --licenses || true

    sdkmanager "platform-tools" \
               "platforms;android-33" \
               "build-tools;33.0.2"
